sonata_admin:
    title: Administration
    title_logo: /images/logo.png
    templates:
        layout: admin/layout.html.twig
    dashboard:
        groups:
            content:
              label: Recrutement
              label_catalogue: admin
              item:
                  - app.admin.offer
                  - app.admin.quiz
                  - app.admin.question
                  - app.admin.tag
#            cms:
#                label: RH
#                label_catalogue: admin
#                item:
#                    - app.admin.candidats

services:
    app.admin.quiz:
        class: AppBundle\Admin\QuizAdmin
        arguments: [~, AppBundle\Entity\Quiz, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Questionnaire }
    app.admin.question:
                class: AppBundle\Admin\QuestionAdmin
                arguments: [~, AppBundle\Entity\Question, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: Question }
    app.admin.offer:
                class: AppBundle\Admin\OfferAdmin
                arguments: [~, AppBundle\Entity\Offer, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: Offres }
    app.admin.tag:
                class: AppBundle\Admin\TagAdmin
                arguments: [~, AppBundle\Entity\Tags, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: Compétences }