offers:
    type:     rest
    resource: AppBundle\Controller\API\OfferController

users:
    type:     rest
    resource: AppBundle\Controller\API\UserController

api:
    resource: AppBundle\Controller\API\DefaultController
    type: rest